import React from "react";
import styles from "./Input_straw.module.css";

const Input_straw = () => (
  <div>
    <div className={styles["container"]}>
      <div className={styles["wrapper"]}>
        <div className={styles["input-wrapper"]}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth="1.5"
            stroke="white"
            className="search-icon"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
            ></path>
          </svg>
          <input type="text" placeholder="Search..." name="" id="" class="" />

          <button className={styles["filter-btn"]}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="white"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 3c2.755 0 5.455.232 8.083.678.533.09.917.556.917 1.096v1.044a2.25 2.25 0 0 1-.659 1.591l-5.432 5.432a2.25 2.25 0 0 0-.659 1.591v2.927a2.25 2.25 0 0 1-1.244 2.013L9.75 21v-6.568a2.25 2.25 0 0 0-.659-1.591L3.659 7.409A2.25 2.25 0 0 1 3 5.818V4.774c0-.54.384-1.006.917-1.096A48.32 48.32 0 0 1 12 3Z"
              ></path>
            </svg>
          </button>

          <div className={styles["pink-overlay"]}></div>

          <div className={styles["blue-overlay"]}></div>

          <div className={styles["gradient-box"]}></div>
        </div>

        <div className={styles["grid-layout"]}>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
          <div className={styles["aspect-square"] + styles["bg-black"]}></div>
        </div>
        <div className={styles["oval-overlay"]}>
          <div className={styles["shadow"]}></div>
        </div>
      </div>
    </div>
  </div>
);

export default Input_straw;
{
  /* If The CSS Is Not Being Applied Properly Due To module.css Not Being Scoped Globally, Delete The Code Above, Uncomment The Code Below, And Paste The CSS Into Your Global.CSS File. This Should Resolve The Issue. */
}
{
  /*
            
        import React from 'react';

        const Input_straw = () => (
         <div>
          <div className="container">
  <div className="wrapper">
    <div className="input-wrapper">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="1.5"
        stroke="white"
        className="search-icon"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
        ></path>
      </svg>
      <input type="text" placeholder="Search..." name="" id="" class="" />

      <button className="filter-btn">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth="1.5"
          stroke="white"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M12 3c2.755 0 5.455.232 8.083.678.533.09.917.556.917 1.096v1.044a2.25 2.25 0 0 1-.659 1.591l-5.432 5.432a2.25 2.25 0 0 0-.659 1.591v2.927a2.25 2.25 0 0 1-1.244 2.013L9.75 21v-6.568a2.25 2.25 0 0 0-.659-1.591L3.659 7.409A2.25 2.25 0 0 1 3 5.818V4.774c0-.54.384-1.006.917-1.096A48.32 48.32 0 0 1 12 3Z"
          ></path>
        </svg>
      </button>

      <div className="pink-overlay"></div>

      <div className="blue-overlay"></div>

      <div className="gradient-box"></div>
    </div>

    <div className="grid-layout">
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
      <div className="aspect-square bg-black"></div>
    </div>
    <div className="oval-overlay">
      <div className="shadow"></div>
    </div>
  </div>
</div>
        </div>
        );

        export default Input_straw;
        
        
         */
}
